### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by yuyan884** [YuyaHayashiBr/protospace-38296#6]
# What
発展カリキュラム 実装課題 (ProtoSpace) を作成したため、動作確認をお願い致します。

# ProtoSpace URL
https://protospace-38296.herokuapp.com/

**Comment by motomuun** [comment]
@YuyaHayashiBr さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ一覧表示機能**

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
画像をクリックしても遷移しません。画像をクリックするとプロトタイプ詳細ページへ遷移するように修正をお願いします。

**プロトタイプ詳細表示機能**

- [x] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されていること**
こちらの投稿者名に「さん」は不要です。取り除くようにお願いします。
<img width="1437" alt="スクリーンショット 2022-08-15 9 08 33" src="https://user-images.githubusercontent.com/65059944/184560013-0e7c566b-a01d-4c5a-95b5-459ce86cc0f9.png">

**コメント機能**

- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
以下のエラーページに遷移します。フォームが空の場合は、詳細ページに留まるように修正をお願いします。
<img width="1440" alt="スクリーンショット 2022-08-15 9 10 10" src="https://user-images.githubusercontent.com/65059944/184560063-3285fb9c-54fa-495d-8d2e-a9530a687986.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yuyan884** [comment]
@motomuun 様

ご確認頂き、ありがとうございます。
ご指摘頂いた内容を修正致します。

また、私個人の管理用にご指摘内容はIssueで管理致します。
[【不良】画像をクリックしてもプロトタイプ詳細ページへ遷移しない](https://github.com/YuyaHayashiBr/protospace-38296/issues/7)
[【不良】投稿者名に「さん」がついている](https://github.com/YuyaHayashiBr/protospace-38296/issues/8)
[【不良】コメントのフォームを空のまま投稿するとエラーとなる](https://github.com/YuyaHayashiBr/protospace-38296/issues/9)

**Comment by yuyan884** [comment]
修正対応致しました。
protospace完了報告フォームも提出済みです。

ご確認のほど、よろしくお願い致します。

**Comment by motomuun** [comment]
@YuyaHayashiBr さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

管理のためにgithubを活用されていて、ツールを使いこなしていらっしゃるのも素晴らしいです！
次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by yuyan884** [comment]
@motomuun 様

早速のご確認ありがとうございます。
それでは、以下のIssueはCloseさせて頂きます。
[【不良】画像をクリックしてもプロトタイプ詳細ページへ遷移しない](https://github.com/YuyaHayashiBr/protospace-38296/issues/7)
[【不良】投稿者名に「さん」がついている](https://github.com/YuyaHayashiBr/protospace-38296/issues/8)
[【不良】コメントのフォームを空のまま投稿するとエラーとなる](https://github.com/YuyaHayashiBr/protospace-38296/issues/9)
